feat: check if the HEAD sha is latest (#1174)
* feat: check HEAD sha

* fix: set shell

* fix: fix unbound variables

* fix: set github-comment variables

* fix: use jq's -r option

* fix: fix var separator

* fix: stop posting comments by github-comment

* fix: revert the change of setup

diff --git a/list-targets/action.yaml b/list-targets/action.yaml
--- a/list-targets/action.yaml
+++ b/list-targets/action.yaml
@@ -27,6 +27,18 @@ runs:
       shell: bash
       env:
         GITHUB_TOKEN: ${{ inputs.github_token }}
+    - name: Check if the commit is latest
+      shell: bash
+      run: |
+        set -euo pipefail
+        LATEST_HEAD_SHA=$(jq -r ".head.sha" $CI_INFO_TEMP_DIR/pr.json)
+        if [ "$HEAD_SHA" != "$LATEST_HEAD_SHA" ]; then
+          echo "::error::The head sha ($HEAD_SHA) isn't latest ($LATEST_HEAD_SHA)."
+          exit 1
+        fi
+      env:
+        HEAD_SHA: ${{github.event.pull_request.head.sha}}
+
     - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
       with:
         name: tfaction-ci-info
