fix: add logs (#2190)
* fix: add logs

* ci: create a dummy target for testing

* ci: fix

* ci: fix

* ci: fix

* ci: fix test

* ci: manage drift issues in test-tfaction

* ci: fix test

* ci: fix permissions

* ci: fix token repository

* test: fix test data

* ci: fix

diff --git a/.github/workflows/wc-create-pr-branch.yaml b/.github/workflows/wc-create-pr-branch.yaml
--- a/.github/workflows/wc-create-pr-branch.yaml
+++ b/.github/workflows/wc-create-pr-branch.yaml
@@ -311,10 +311,7 @@ jobs:
     timeout-minutes: 15
     runs-on: ubuntu-latest
     needs: [create-pr-branch]
-    permissions:
-      contents: write
-      pull-requests: write
-      issues: write
+    permissions: {}
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
@@ -346,37 +343,49 @@ jobs:
           permissions: >-
             {
               "pull_requests": "write",
-              "contents": "write"
+              "contents": "write",
+              "issues": "write"
             }
           repositories: >-
-            ["${{github.event.repository.name}}"]
+            ["test-tfaction"]
 
       - name: Install dependencies
         uses: ./install
 
-      - name: Test create-drift-issues
-        uses: ./js
-        id: create-drift-issues
-        with:
-          action: create-drift-issues
-        env:
-          TFACTION_CONFIG: js/test/tfaction-root.yaml
+      - name: Create a dummy working directory
+        run: mkdir -p "js/test/aws/foo/dev-${GITHUB_RUN_ID}"
+      - name: Create a dummy tfaction.yaml
+        run: echo '{}' > "js/test/aws/foo/dev-${GITHUB_RUN_ID}/tfaction.yaml"
+      - run: git add "js/test/aws/foo/dev-${GITHUB_RUN_ID}"
       - name: Test get-or-create-drift-issue
         uses: ./js
         id: get-or-create-drift-issue
         with:
+          github_token: ${{steps.token.outputs.token}}
           action: get-or-create-drift-issue
         env:
           TFACTION_CONFIG: js/test/tfaction-root.yaml
-          TFACTION_TARGET: js/test/aws/foo/dev
+          TFACTION_TARGET: js/test/aws/foo/dev-${{github.run_id}}
+      - run: git reset HEAD "js/test/aws/foo/dev-${GITHUB_RUN_ID}"
+      - name: Remove a dummy working directory
+        run: rm -R "js/test/aws/foo/dev-${GITHUB_RUN_ID}"
+      - run: sleep 5
+      - name: Test create-drift-issues
+        uses: ./js
+        id: create-drift-issues
+        with:
+          github_token: ${{steps.token.outputs.token}}
+          action: create-drift-issues
+        env:
+          TFACTION_CONFIG: js/test/tfaction-root.yaml
 
       - name: Test env
         run: |
-          if [ "$TFACTION_DRIFT_ISSUE_NUMBER" != "2183" ]; then
-            echo "::error:: TFACTION_DRIFT_ISSUE_NUMBER is not expected" >&2
+          if [ -z "$TFACTION_DRIFT_ISSUE_NUMBER" ]; then
+            echo "::error:: TFACTION_DRIFT_ISSUE_NUMBER is not set" >&2
             exit 1
           fi
-          if [ "$TFACTION_DRIFT_ISSUE_STATE" != "CLOSED" ]; then
+          if [ "$TFACTION_DRIFT_ISSUE_STATE" != "open" ]; then
             echo "::error:: TFACTION_DRIFT_ISSUE_STATE is not expected" >&2
             exit 1
           fi
