ci: fix test

diff --git a/.github/workflows/wc-create-pr-branch.yaml b/.github/workflows/wc-create-pr-branch.yaml
--- a/.github/workflows/wc-create-pr-branch.yaml
+++ b/.github/workflows/wc-create-pr-branch.yaml
@@ -381,11 +381,11 @@ jobs:
 
       - name: Test env
         run: |
-          if [ "$TFACTION_DRIFT_ISSUE_NUMBER" != "2183" ]; then
-            echo "::error:: TFACTION_DRIFT_ISSUE_NUMBER is not expected" >&2
+          if [ -z "$TFACTION_DRIFT_ISSUE_NUMBER" ]; then
+            echo "::error:: TFACTION_DRIFT_ISSUE_NUMBER is not set" >&2
             exit 1
           fi
-          if [ "$TFACTION_DRIFT_ISSUE_STATE" != "CLOSED" ]; then
+          if [ "$TFACTION_DRIFT_ISSUE_STATE" != "OPEN" ]; then
             echo "::error:: TFACTION_DRIFT_ISSUE_STATE is not expected" >&2
             exit 1
           fi
