ci: split jobs

diff --git a/.github/workflows/wc-create-pr-branch.yaml b/.github/workflows/wc-create-pr-branch.yaml
--- a/.github/workflows/wc-create-pr-branch.yaml
+++ b/.github/workflows/wc-create-pr-branch.yaml
@@ -101,22 +101,6 @@ jobs:
       - name: Install dependencies
         uses: ./install
 
-      - name: Test create-drift-issues
-        uses: ./js
-        id: create-drift-issues
-        with:
-          action: create-drift-issues
-        env:
-          TFACTION_CONFIG: js/test/tfaction-root.yaml
-      - name: Test get-or-create-drift-issue
-        uses: ./js
-        id: get-or-create-drift-issue
-        with:
-          action: get-or-create-drift-issue
-        env:
-          TFACTION_CONFIG: js/test/tfaction-root.yaml
-          TFACTION_TARGET: js/test/aws/foo/dev
-
       - name: Test js/get-target-config
         uses: ./js
         id: js-target-config
@@ -322,6 +306,80 @@ jobs:
           JS_LIST_MODULE_CALLERS: ${{ toJSON(steps.js-list-module-callers.outputs) }}
           LIST_TARGETS_WITH_CHANGED_FILES: ${{ toJSON(steps.list-targets-with-changed-files.outputs) }}
           JS_LIST_TARGETS_WITH_CHANGED_FILES: ${{ toJSON(steps.js-list-targets-with-changed-files.outputs) }}
+
+  test-drift-detection:
+    timeout-minutes: 15
+    runs-on: ubuntu-latest
+    needs: [create-pr-branch]
+    permissions:
+      contents: write
+      pull-requests: write
+      issues: write
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          persist-credentials: false
+      - run: gh pr checkout "$PR"
+        if: inputs.pr != ''
+        env:
+          GITHUB_TOKEN: ${{github.token}}
+          PR: ${{inputs.pr}}
+      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
+        with:
+          aqua_version: v2.41.0
+        env:
+          GITHUB_TOKEN: ${{github.token}}
+      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
+        with:
+          path: js/dist
+          name: js
+      - name: Replace suzuki-shusnuke/tfaction/*@main with ./*
+        run: |
+          git ls-files | grep -v ".github" | xargs sed -i -E 's|uses: suzuki-shunsuke/tfaction/(.*)@main|uses: ./\1|'
+      - name: Install dependencies
+        uses: ./install
+      - id: token
+        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
+        with:
+          app_id: ${{secrets.gh_app_id}}
+          private_key: ${{secrets.gh_app_private_key}}
+          permissions: >-
+            {
+              "pull_requests": "write",
+              "contents": "write"
+            }
+          repositories: >-
+            ["${{github.event.repository.name}}"]
+
+      - name: Install dependencies
+        uses: ./install
+
+      - name: Test create-drift-issues
+        uses: ./js
+        id: create-drift-issues
+        with:
+          action: create-drift-issues
+        env:
+          TFACTION_CONFIG: js/test/tfaction-root.yaml
+      - name: Test get-or-create-drift-issue
+        uses: ./js
+        id: get-or-create-drift-issue
+        with:
+          action: get-or-create-drift-issue
+        env:
+          TFACTION_CONFIG: js/test/tfaction-root.yaml
+          TFACTION_TARGET: js/test/aws/foo/dev
+
+      - name: Test env
+        run: |
+          if [ "$TFACTION_DRIFT_ISSUE_NUMBER" != "2183" ]; then
+            echo "::error:: TFACTION_DRIFT_ISSUE_NUMBER is not expected" >&2
+            exit 1
+          fi
+          if [ "$TFACTION_DRIFT_ISSUE_STATE" != "CLOSED" ]; then
+            echo "::error:: TFACTION_DRIFT_ISSUE_STATE is not expected" >&2
+            exit 1
+          fi
 
   test-opentofu:
     timeout-minutes: 15
